import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./scss/reset.scss";
import { Navigation } from "../app/components/ui/nav/page";
import { BlurOverlay } from "../app/components/ui/blur/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home | Jakob Tidemand - Frontend developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <BlurOverlay></BlurOverlay>
        {children}
      </body>
    </html>
  );
}
