// "use client";
// import type { Metadata } from "next";
// import "./scss/reset.scss";
// import { Navigation, BlurOverlay } from "./components/ui";
// import React from "react";
// import { LenisSmoothScroll, Cursor } from "./components/effects/";

// // export const metadata: Metadata = {
// //   title: "Home | Jakob Tidemand - Frontend developer",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <Cursor />
//         <Navigation />
//         <BlurOverlay></BlurOverlay>
//         <LenisSmoothScroll>{children}</LenisSmoothScroll>
//       </body>
//     </html>
//   );
// }
"use client";
import type { Metadata } from "next";
import "./scss/reset.scss";
import { Navigation, BlurOverlay } from "./components/ui";
import React from "react";
import { LenisSmoothScroll, Cursor } from "./components/effects/";
import { CursorProvider } from "./components/context/cursorContext/page";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CursorProvider>
          <Cursor />
          <Navigation />
          <BlurOverlay />
          <LenisSmoothScroll>{children}</LenisSmoothScroll>
        </CursorProvider>
      </body>
    </html>
  );
}
